name: Build Changes
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build the mod
        run: mvn -B clean package

      - name: Build the mod for Android
        if: runner.os == 'Linux'
        run: |
          export PATH=$ANDROID_HOME/build-tools/32.0.0:$PATH
          cd tools && mvn install
          cd ..
          mvn riim-tools:dex

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: riim
          path: target/riim-*.jar
