name: Build Changes
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Build the mod
        run: mvn -B clean package

      - name: Build the mod for Android
        if: runner.os == 'Linux'
        run: |
          export PATH=$ANDROID_HOME/build-tools/32.0.0:$PATH
          ./scripts/package_android.sh -api 32 -game v135.2 target/riim-*.jar

      - uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: riim
          path: target/riim-*.jar
